### ISSUE TITLE
Suggestion: Remove unneeded spaces in CSS after property names.

### ISSUE THREAD

**Issue by josephtkim** [juliuso/prj-rev-bwfs-dasmoto#4]
Adding spaces to line up columns can get tedious very quickly, and is not necessary. It is usually best practice to just have a single space after the colon, like so

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
